version: "3.8"

x-base: &base-hregion
  image: lucasfs/hbase-armhf:hregion
  volumes:
    - /mnt/storage/hdfs:/hadoop-data/hdfs/datanode
  networks:
    - cluster_net
  env_file:
    - ./hbase.env

networks:
  cluster_net:
    external: true
    name: hbase-net  

services:
  #####################
  #   HBASE MASTER    #
  #####################
  hmaster:
    image: lucasfs/hbase-armhf:hmaster
    hostname: hmaster
    networks:
      - cluster_net
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hbase.env
    deploy: 
      &deploy-conf
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-06
    volumes:
      - /mnt/storage/hdfs:/hadoop-data/hdfs/namenode
    ports:
      - target: 9870
        published: 9870
        mode: host

      - target: 16010
        published: 16010
        mode: host

  ###########################
  #   HBASE REGIONSERVERS   #
  ###########################
  hregion1:
    <<: *base-hregion
    hostname: hregion1
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion1
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-01

  hregion2:
    <<: *base-hregion
    hostname: hregion2
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion2
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-02

  hregion3:
    <<: *base-hregion
    hostname: hregion3
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion3
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-03

  hregion4:
    <<: *base-hregion
    hostname: hregion4
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion4
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-04

  hregion5:
    <<: *base-hregion
    hostname: hregion5
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion5
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-05

  hregion6:
    <<: *base-hregion
    hostname: hregion6
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion6
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-07

  hregion7:
    <<: *base-hregion
    hostname: hregion7
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion7
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-08

  hregion8:
    <<: *base-hregion
    hostname: hregion8
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion8
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-09
  
  hregion9:
    <<: *base-hregion
    hostname: hregion9
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion9
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-10

  hregion10:
    <<: *base-hregion
    hostname: hregion10
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion10
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-11

  hregion11:
    <<: *base-hregion
    hostname: hregion11
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion11
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-12

  hregion12:
    <<: *base-hregion
    hostname: hregion12
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion12
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-13

  hregion13:
    <<: *base-hregion
    hostname: hregion13
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion13
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-14

  hregion14:
    <<: *base-hregion
    hostname: hregion14
    environment:
      - HBASE_CONF_hbase_regionserver_hostname=hregion14
    deploy:
      << : *deploy-conf
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-15