version: "3.8"

services:
  #####################
  #   HDFS NAMENODE   #
  #####################
  namenode:
    image: lucasfs/hadoop-namenode
    networks:
      - cluster_net
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - target: 9870
        published: 9870
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-01

  #####################
  #   HDFS DATANODE   #
  #####################
  datanode:
    image: lucasfs/hadoop-datanode
    networks:
      - cluster_net
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-02
  
  #####################
  #   HBASE MASTER    #
  #####################
  hbase-master:
    image: lucasfs/hbase-hmaster
    networks:
      - cluster_net
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-01
    env_file:
      - ./hbase.env
    ports:
      - target: 16010
        published: 16010
        mode: host

  ##########################
  #   HBASE REGIONSERVER   #
  ##########################
  hbase-regionserver:
    image: lucasfs/hbase-hregionserver
      - cluster_net
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-02
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver


volumes:
  datanode:
  namenode:

networks:
  cluster_net:
    external: true
    name: hadoop-net  