version: "3.8"

services:
    
  #####################
  #   HBASE MASTER    #
  #####################
  master:
    image: lucasfs/hbase-hmaster:hbase-1.4.13 
    hostname: master
    networks:
      - cluster_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-01
    env_file:
      - ./hbase.env
    volumes: 
      - ${PWD}/regionservers:/etc/hbase/regionservers
    environment:
      HBASE_REGIONSERVERS: /etc/hbase/regionservers
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 zoo1:2181 zoo2:2181"
    # ports:
      # - target: 16000
      #   published: 16000
      #   mode: host

      # - target: 16010
      #   published: 16010
      #   mode: host

      # - target: 2888
      #   published: 2888
      #   mode: host

      # - target: 3888
      #   published: 3888
      #   mode: host

      # - target: 2181
      #   published: 2181
      #   mode: host
 
  ##########################
  #   HBASE REGIONSERVER   #
  ##########################
  regionserver-1:
    image: lucasfs/hbase-hregionserver:hbase-1.4.13
    hostname: regionserver-1
    networks:
      - cluster_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-02
    # ports:
    #   - target: 16020
    #     published: 16020
    #     mode: host
      
    #   - target: 16030
    #     published: 16030
    #     mode: host

    #   - target: 2888
    #     published: 2888
    #     mode: host

    #   - target: 3888
    #     published: 3888
    #     mode: host

    #   - target: 2181
    #     published: 2181
    #     mode: host

    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: regionserver-1
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 master:16010 zoo1:2181 zoo2:2181"
  
  ##########################
  #   HBASE REGIONSERVER   #
  ##########################
  regionserver-2:
    image: lucasfs/hbase-hregionserver:hbase-1.4.13
    hostname: regionserver-2
    networks:
      - cluster_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        # max_attempts: 3
        # window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi3-01
    # ports:
    #   - target: 16020
    #     published: 16020
    #     mode: host
      
    #   - target: 16030
    #     published: 16030
    #     mode: host

    #   - target: 2888
    #     published: 2888
    #     mode: host

    #   - target: 3888
    #     published: 3888
    #     mode: host

    #   - target: 2181
    #     published: 2181
    #     mode: host

    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: regionserver-2
      SERVICE_PRECONDITION: "namenode:9000 datanode2:50075 master:16010 zoo1:2181 zoo2:2181"


networks:
  cluster_net:
    external: true
    name: hadoop-net  
