version: "3.8"

services:
  #####################
  #   HDFS NAMENODE   #
  #####################
  namenode:
    image: lucasfs/hadoop-namenode
    networks:
      - cluster_net
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
#    ports:
#      - target: 9870
#        published: 9870
#        mode: host
#    ports:
#      - 9000:9000 
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-01

  #####################
  #   HDFS DATANODE   #
  #####################
  datanode:
    image: lucasfs/hadoop-datanode
    networks:
      - cluster_net
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr      
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-02

  
  #####################
  #   HBASE MASTER    #
  #####################
  master:
    image: lucasfs/hbase-hmaster 
    networks:
      - cluster_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-01
    env_file:
      - ./hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075"
#    ports:
#      - target: 16010
#        published: 16010
#        mode: host
    ports:
      - 16000:16000
      - 2888:2888
      - 3888:3888
      - 2181:2181
  ##########################
  #   HBASE REGIONSERVER   #
  ##########################
  regionserver:
    image: lucasfs/hbase-hregionserver
    networks:
      - cluster_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
#        max_replicas_per_node: 1
        constraints:
          - node.hostname == rpi4-02
    ports:
      - 16020:16020
      - 2888:2888
      - 3888:3888
      - 2181:2181
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: regionserver
      SERVICE_PRECONDITION: "namenode:9000 datanode:50075 master:16000"


volumes:
  datanode:
  namenode:

networks:
  cluster_net:
    external: true
    name: hadoop-net  
