version: '3.3'

services:
  namenode:
    image: hadoop-namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - hadoop-net

  datanode:
    image: hadoop-datanode
    volumes:
      - datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - hadoop-net

  resourcemanager:
    image: hadoop-resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
    networks:
      - hadoop-net

  nodemanager:
    image: hadoop-nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - hadoop-net

  historyserver:
    image: hadoop-historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - hadoop-net

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  hadoop-net:
    driver: overlay
    attachable: true

